/* tslint:disable */
/* eslint-disable */
/**
 * ClassroomMgmtSys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from './runtime';

/**
 *
 * @export
 * @interface InlineObject
 */
export interface InlineObject14 {
  id: number;
}

export function InlineObject14FromJSON(json: any): InlineObject14 {
  return InlineObject14FromJSONTyped(json, false);
}

export function InlineObject14FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject14 {
  if ((json === undefined) || (json === null)) {
    return json;
  }
  return {
    'id': json['id']
  };
}

export function InlineObject14ToJSON(value?: InlineObject14 | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    'id': value.id,
  };
}


