/* tslint:disable */
/* eslint-disable */
/**
 * ClassroomMgmtSys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from './runtime';

/**
 *
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  monday_1: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  monday_2: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  monday_3: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  tuesday_1: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  tuesday_2: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  tuesday_3: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  wednesday_1: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  wednesday_2: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  wednesday_3: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  thursday_1: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  thursday_2: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  thursday_3: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  friday_1: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  friday_2: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject
   */
  friday_3: number;
}

export function InlineObjectFromJSON(json: any): InlineObject {
  return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
  if ((json === undefined) || (json === null)) {
    return json;
  }
  return {

    'monday_1': json['monday_1'],
    'monday_2': json['monday_2'],
    'monday_3': json['monday_3'],
    'tuesday_1': json['tuesday_1'],
    'tuesday_2': json['tuesday_2'],
    'tuesday_3': json['tuesday_3'],
    'wednesday_1': json['wednesday_1'],
    'wednesday_2': json['wednesday_2'],
    'wednesday_3': json['wednesday_3'],
    'thursday_1': json['thursday_1'],
    'thursday_2': json['thursday_2'],
    'thursday_3': json['thursday_3'],
    'friday_1': json['friday_1'],
    'friday_2': json['friday_2'],
    'friday_3': json['friday_3'],
  };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {

    'monday_1': value.monday_1,
    'monday_2': value.monday_2,
    'monday_3': value.monday_3,
    'tuesday_1': value.tuesday_1,
    'tuesday_2': value.tuesday_2,
    'tuesday_3': value.tuesday_3,
    'wednesday_1': value.wednesday_1,
    'wednesday_2': value.wednesday_2,
    'wednesday_3': value.wednesday_3,
    'thursday_1': value.thursday_1,
    'thursday_2': value.thursday_2,
    'thursday_3': value.thursday_3,
    'friday_1': value.friday_1,
    'friday_2': value.friday_2,
    'friday_3': value.friday_3,
  };
}


