/* tslint:disable */
/* eslint-disable */
/**
 * ClassroomMgmtSys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from './runtime';
/**
 *
 * @export
 * @interface InlineObject9
 */
export interface InlineObject9 {
    /**
     *
     * @type {number}
     * @memberof InlineObject9
     */
    classId: number;
    className: string;
    /**
     *
     * @type {string}
     * @memberof InlineObject9
     */
    cmdName: string;
    /**
     *
     * @type {number}
     * @memberof InlineObject9
     */
    cmdId: number;
}

export function InlineObject9FromJSON(json: any): InlineObject9 {
    return InlineObject9FromJSONTyped(json, false);
}

export function InlineObject9FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject9 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'classId': json['class_id'],
        'className': json['class_name'],
        'cmdName': json['cmd_name'],
        'cmdId': json['cmd_id'],
    };
}

export function InlineObject9ToJSON(value?: InlineObject9 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'class_id': value.classId,
        'class_name': value.className,
        'cmd_name': value.cmdName,
        'cmd_id': value.cmdId,
    };
}


