/* tslint:disable */
/* eslint-disable */
/**
 * ClassroomMgmtSys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from './runtime';
/**
 *
 * @export
 * @interface InlineObject7
 */
export interface InlineObject7 {
    /**
     *
     * @type {number}
     * @memberof InlineObject7
     */
    uid: number;
    /**
     *
     * @type {string}
     * @memberof InlineObject7
     */
    newPass: string;
    /**
     *
     * @type {string}
     * @memberof InlineObject7
     */
    oldPass?: string;
}

export function InlineObject7FromJSON(json: any): InlineObject7 {
    return InlineObject7FromJSONTyped(json, false);
}

export function InlineObject7FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject7 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'uid': json['uid'],
        'newPass': json['new_pass'],
        'oldPass': !exists(json, 'old_pass') ? undefined : json['old_pass'],
    };
}

export function InlineObject7ToJSON(value?: InlineObject7 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'uid': value.uid,
        'new_pass': value.newPass,
        'old_pass': value.oldPass,
    };
}


