/* tslint:disable */
/* eslint-disable */
/**
 * ClassroomMgmtSys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from './runtime';
/**
 *
 * @export
 * @interface InlineObject8
 */
export interface InlineObject8 {
    /**
     *
     * @type {number}
     * @memberof InlineObject8
     */
    uid: number;
    /**
     *
     * @type {string}
     * @memberof InlineObject8
     */
    oldPass: string;
    /**
     *
     * @type {string}
     * @memberof InlineObject8
     */
    newPass: string;
}

export function InlineObject8FromJSON(json: any): InlineObject8 {
    return InlineObject8FromJSONTyped(json, false);
}

export function InlineObject8FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject8 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'uid': json['uid'],
        'oldPass': json['old_pass'],
        'newPass': json['new_pass'],
    };
}

export function InlineObject8ToJSON(value?: InlineObject8 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'uid': value.uid,
        'old_pass': value.oldPass,
        'new_pass': value.newPass,
    };
}


